/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ClientKaroGame;

import java.awt.Color;

/**
 *
 * @author tuong
 */
public class PanelMenu2 extends javax.swing.JPanel {
    
    public PanelMenu2(String nameClient, String nameServer) {
        initComponents();
        lbNameClient.setText(nameClient);
        lbNameClient.setForeground(Color.RED);
        lbNameServer.setText(nameServer);
        lbNameServer.setForeground(Color.BLUE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNameClient = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbNameServer = new javax.swing.JLabel();
        btnDisconect = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(300, 500));

        lbNameClient.setBackground(new java.awt.Color(255, 255, 204));
        lbNameClient.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNameClient.setText("Name Client");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("VS");

        lbNameServer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNameServer.setText("Name Server");

        btnDisconect.setText("Disconect");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNameServer)
                            .addComponent(lbNameClient)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnDisconect)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNameClient)
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(lbNameServer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(btnDisconect)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisconect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbNameClient;
    private javax.swing.JLabel lbNameServer;
    // End of variables declaration//GEN-END:variables
}
