/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SwingInterface;

import DatabaseDriver.*;
import Manager.*;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.rowset.CachedRowSet;

/**
 *
 * @author Tan
 */
public class MainFrame extends javax.swing.JFrame {
    private DatabaseDriver dbDriver;
    private studentTableModel stdTblMdl;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        this.dbDriver = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        interlFrmStudentManager = new javax.swing.JInternalFrame();
        studentToolbar = new javax.swing.JToolBar();
        btnNewStudent = new javax.swing.JButton();
        btnUpdateStudent = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        studentScrollBar = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        interFrmcourseManager = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        menuOption = new javax.swing.JMenu();
        menuOptionConnect = new javax.swing.JMenuItem();
        menuOptionExit = new javax.swing.JMenuItem();
        menuManage = new javax.swing.JMenu();
        menuManageStudent = new javax.swing.JMenuItem();
        menuManageCourse = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Manager");

        interlFrmStudentManager.setClosable(true);
        interlFrmStudentManager.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        interlFrmStudentManager.setMaximizable(true);
        interlFrmStudentManager.setResizable(true);
        interlFrmStudentManager.setTitle("Student Manager");
        interlFrmStudentManager.setVisible(true);

        studentToolbar.setFloatable(false);
        studentToolbar.setRollover(true);

        btnNewStudent.setText("New");
        btnNewStudent.setFocusable(false);
        btnNewStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewStudentActionPerformed(evt);
            }
        });
        studentToolbar.add(btnNewStudent);

        btnUpdateStudent.setText("Update");
        btnUpdateStudent.setFocusable(false);
        btnUpdateStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdateStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        studentToolbar.add(btnUpdateStudent);

        btnDeleteStudent.setText("Delete");
        btnDeleteStudent.setFocusable(false);
        btnDeleteStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        studentToolbar.add(btnDeleteStudent);

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        studentScrollBar.setViewportView(studentTable);

        javax.swing.GroupLayout interlFrmStudentManagerLayout = new javax.swing.GroupLayout(interlFrmStudentManager.getContentPane());
        interlFrmStudentManager.getContentPane().setLayout(interlFrmStudentManagerLayout);
        interlFrmStudentManagerLayout.setHorizontalGroup(
            interlFrmStudentManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
            .addComponent(studentScrollBar)
        );
        interlFrmStudentManagerLayout.setVerticalGroup(
            interlFrmStudentManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interlFrmStudentManagerLayout.createSequentialGroup()
                .addComponent(studentToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentScrollBar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 164, Short.MAX_VALUE))
        );

        interlFrmStudentManager.setBounds(180, 20, 210, 140);
        desktopPane.add(interlFrmStudentManager, javax.swing.JLayeredPane.DEFAULT_LAYER);
        try {
            interlFrmStudentManager.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        interFrmcourseManager.setClosable(true);
        interFrmcourseManager.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        interFrmcourseManager.setMaximizable(true);
        interFrmcourseManager.setResizable(true);
        interFrmcourseManager.setTitle("Course Manager");
        interFrmcourseManager.setVisible(true);

        javax.swing.GroupLayout interFrmcourseManagerLayout = new javax.swing.GroupLayout(interFrmcourseManager.getContentPane());
        interFrmcourseManager.getContentPane().setLayout(interFrmcourseManagerLayout);
        interFrmcourseManagerLayout.setHorizontalGroup(
            interFrmcourseManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 676, Short.MAX_VALUE)
        );
        interFrmcourseManagerLayout.setVerticalGroup(
            interFrmcourseManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );

        interFrmcourseManager.setBounds(0, 0, 180, 140);
        desktopPane.add(interFrmcourseManager, javax.swing.JLayeredPane.DEFAULT_LAYER);
        try {
            interFrmcourseManager.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        menuBar.setToolTipText("Student Manager");

        menuOption.setText("Option");

        menuOptionConnect.setText("Connect");
        menuOptionConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOptionConnectActionPerformed(evt);
            }
        });
        menuOption.add(menuOptionConnect);

        menuOptionExit.setText("Exit");
        menuOptionExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOptionExitActionPerformed(evt);
            }
        });
        menuOption.add(menuOptionExit);

        menuBar.add(menuOption);

        menuManage.setText("Manage");

        menuManageStudent.setText("Students");
        menuManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageStudentActionPerformed(evt);
            }
        });
        menuManage.add(menuManageStudent);

        menuManageCourse.setText("Courses");
        menuManage.add(menuManageCourse);

        menuBar.add(menuManage);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOptionConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOptionConnectActionPerformed
        // TODO add your handling code here:
        DBInfoForm dialog = new DBInfoForm(this, true); 
        if(dialog.getSignal()){
            this.dbDriver = new DatabaseDriver(dialog.getTxtServer(), dialog.getTxtUserName(), dialog.getTxtPsw());
        }
    }//GEN-LAST:event_menuOptionConnectActionPerformed

    private void btnNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewStudentActionPerformed

    private void menuOptionExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOptionExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuOptionExitActionPerformed

    private void menuManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageStudentActionPerformed
        // TODO add your handling code here:
        if(this.dbDriver != null){
            if(this.interlFrmStudentManager.isVisible() == false){
                try {
                    CachedRowSet studentRowSet = this.dbDriver.selectFrom("Students");
                    this.stdTblMdl = new studentTableModel(studentRowSet);
                    this.studentTable.setModel(stdTblMdl);
                    
                    this.interlFrmStudentManager.setVisible(true);
                    this.interlFrmStudentManager.moveToFront();
                    this.interlFrmStudentManager.setSelected(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                try {
                    this.interlFrmStudentManager.moveToFront();
                    this.interlFrmStudentManager.setSelected(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            this.menuOptionConnectActionPerformed(evt);
            this.menuManageStudentActionPerformed(evt);
        }
    }//GEN-LAST:event_menuManageStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mainFrame = new MainFrame();
                mainFrame.setVisible(true);
                mainFrame.interlFrmStudentManager.setVisible(false);
                mainFrame.interFrmcourseManager.setVisible(false);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnNewStudent;
    private javax.swing.JButton btnUpdateStudent;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JInternalFrame interFrmcourseManager;
    private javax.swing.JInternalFrame interlFrmStudentManager;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuManage;
    private javax.swing.JMenuItem menuManageCourse;
    private javax.swing.JMenuItem menuManageStudent;
    private javax.swing.JMenu menuOption;
    private javax.swing.JMenuItem menuOptionConnect;
    private javax.swing.JMenuItem menuOptionExit;
    private javax.swing.JScrollPane studentScrollBar;
    private javax.swing.JTable studentTable;
    private javax.swing.JToolBar studentToolbar;
    // End of variables declaration//GEN-END:variables
}
