/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SwingInterface;

/**
 *
 * @author Tan
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        internalFrame = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        menuOption = new javax.swing.JMenu();
        menuOptionConnect = new javax.swing.JMenuItem();
        menuOptionExit = new javax.swing.JMenuItem();
        menuManage = new javax.swing.JMenu();
        menuManageStudent = new javax.swing.JMenuItem();
        menuManageCourse = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Manager");

        internalFrame.setVisible(true);

        javax.swing.GroupLayout internalFrameLayout = new javax.swing.GroupLayout(internalFrame.getContentPane());
        internalFrame.getContentPane().setLayout(internalFrameLayout);
        internalFrameLayout.setHorizontalGroup(
            internalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );
        internalFrameLayout.setVerticalGroup(
            internalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        internalFrame.setBounds(10, 20, 210, 140);
        desktopPane.add(internalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        menuBar.setToolTipText("Student Manager");

        menuOption.setText("Option");

        menuOptionConnect.setText("Connect");
        menuOptionConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOptionConnectActionPerformed(evt);
            }
        });
        menuOption.add(menuOptionConnect);

        menuOptionExit.setText("Exit");
        menuOption.add(menuOptionExit);

        menuBar.add(menuOption);

        menuManage.setText("Manage");

        menuManageStudent.setText("Students");
        menuManage.add(menuManageStudent);

        menuManageCourse.setText("Courses");
        menuManage.add(menuManageCourse);

        menuBar.add(menuManage);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOptionConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOptionConnectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuOptionConnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JInternalFrame internalFrame;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuManage;
    private javax.swing.JMenuItem menuManageCourse;
    private javax.swing.JMenuItem menuManageStudent;
    private javax.swing.JMenu menuOption;
    private javax.swing.JMenuItem menuOptionConnect;
    private javax.swing.JMenuItem menuOptionExit;
    // End of variables declaration//GEN-END:variables
}
