/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SwingInterface;

/**
 *
 * @author Tan
 */
public class MainFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        studentManager = new javax.swing.JInternalFrame();
        studentToolbar = new javax.swing.JToolBar();
        btnNewStudent = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        courseManager = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        menuOption = new javax.swing.JMenu();
        menuOptionConnect = new javax.swing.JMenuItem();
        menuOptionExit = new javax.swing.JMenuItem();
        menuManage = new javax.swing.JMenu();
        menuManageStudent = new javax.swing.JMenuItem();
        menuManageCourse = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Manager");

        studentManager.setClosable(true);
        studentManager.setMaximizable(true);
        studentManager.setTitle("Student Manager");
        studentManager.setVisible(true);

        studentToolbar.setFloatable(false);
        studentToolbar.setRollover(true);

        btnNewStudent.setText("New");
        btnNewStudent.setFocusable(false);
        btnNewStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewStudent.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewStudentActionPerformed(evt);
            }
        });
        studentToolbar.add(btnNewStudent);

        jButton1.setText("Update");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        studentToolbar.add(jButton1);

        jButton2.setText("Delete");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        studentToolbar.add(jButton2);

        javax.swing.GroupLayout studentManagerLayout = new javax.swing.GroupLayout(studentManager.getContentPane());
        studentManager.getContentPane().setLayout(studentManagerLayout);
        studentManagerLayout.setHorizontalGroup(
            studentManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        studentManagerLayout.setVerticalGroup(
            studentManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentManagerLayout.createSequentialGroup()
                .addComponent(studentToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 229, Short.MAX_VALUE))
        );

        studentManager.setBounds(180, 20, 210, 140);
        desktopPane.add(studentManager, javax.swing.JLayeredPane.DEFAULT_LAYER);
        try {
            studentManager.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        courseManager.setClosable(true);
        courseManager.setMaximizable(true);
        courseManager.setTitle("Course Manager");
        courseManager.setVisible(true);

        javax.swing.GroupLayout courseManagerLayout = new javax.swing.GroupLayout(courseManager.getContentPane());
        courseManager.getContentPane().setLayout(courseManagerLayout);
        courseManagerLayout.setHorizontalGroup(
            courseManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        courseManagerLayout.setVerticalGroup(
            courseManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        courseManager.setBounds(0, 0, 180, 140);
        desktopPane.add(courseManager, javax.swing.JLayeredPane.DEFAULT_LAYER);
        try {
            courseManager.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        menuBar.setToolTipText("Student Manager");

        menuOption.setText("Option");

        menuOptionConnect.setText("Connect");
        menuOptionConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOptionConnectActionPerformed(evt);
            }
        });
        menuOption.add(menuOptionConnect);

        menuOptionExit.setText("Exit");
        menuOption.add(menuOptionExit);

        menuBar.add(menuOption);

        menuManage.setText("Manage");

        menuManageStudent.setText("Students");
        menuManage.add(menuManageStudent);

        menuManageCourse.setText("Courses");
        menuManage.add(menuManageCourse);

        menuBar.add(menuManage);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOptionConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOptionConnectActionPerformed
        // TODO add your handling code here:
        DBInfoForm dialog = new DBInfoForm(this, true); 
        if(dialog.getSignal()){
            System.out.println(dialog.getTxtPsw());
            System.out.println(dialog.getTxtServer());
            System.out.println(dialog.getTxtUserName());
        }
    }//GEN-LAST:event_menuOptionConnectActionPerformed

    private void btnNewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mainFrame = new MainFrame();
                mainFrame.setVisible(true);
                mainFrame.studentManager.setVisible(false);
                mainFrame.courseManager.setVisible(false);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewStudent;
    private javax.swing.JInternalFrame courseManager;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuManage;
    private javax.swing.JMenuItem menuManageCourse;
    private javax.swing.JMenuItem menuManageStudent;
    private javax.swing.JMenu menuOption;
    private javax.swing.JMenuItem menuOptionConnect;
    private javax.swing.JMenuItem menuOptionExit;
    private javax.swing.JInternalFrame studentManager;
    private javax.swing.JToolBar studentToolbar;
    // End of variables declaration//GEN-END:variables
}
